const eventList = {
    "events":[
        {"id":"1", "enumeration":"EVT_PLC_NODE_JOINED_INDICATION", "description":"Node meter joined to PAN", "severity":"Info"},
        {"id":"2", "enumeration":"EVT_PLC_NODE_ROUTE_DISCOVERED", "description":"Node route discovered", "severity":"Info"},
        {"id":"3", "enumeration":"EVT_PLC_NODE_LEAVE_INDICATION", "description":"Node left PAN network", "severity":"Info"},
        {"id":"4", "enumeration":"EVT_PLC_NODE_LEAVE_CONFORMATION", "description":"Node kicked off from PAN network", "severity":"Info"},
        {"id":"5", "enumeration":"EVT_PLC_NETWORK_CFM", "description":"G3PLC PAN network start", "severity":"Info"},
        {"id":"6", "enumeration":"EVT_PLC_NODE_JOIN_DECLINED", "description":"Node join to PAN declined couse", "severity":"Info"},
        {"id":"7", "enumeration":"EVT_PLC_NODE_ROUTE_ERROR", "description":"Node route discover error", "severity":"Info"},
        {"id":"200", "enumeration":"EVT_RS485_S650_ALARM", "description":"S650 meter alarm", "severity":"Info"},
        {"id":"300", "enumeration":"EVT_PLC_METER_JOINED", "description":"G3 PLC meter joined to PAN", "severity":"Info"},
        {"id":"301", "enumeration":"EVT_PLC_METER_REMOVED", "description":"Meter removed from PAN network", "severity":"Info"},
        {"id":"500", "enumeration":"EVT_SYS_POWER_FAIL", "description":"Power fail", "severity":"Warning"},
        {"id":"501", "enumeration":"EVT_SYS_POWER_RETURN", "description":"Power return", "severity":"Info"},
        {"id":"502", "enumeration":"EVT_SYS_POWER_BACKUP_LOW", "description":"Backup power supply low", "severity":"Warning"},
        {"id":"503", "enumeration":"EVT_SYS_POWER_BACKUP_EMPTY", "description":"Backup power supply empty", "severity":"Warning"},
        {"id":"504", "enumeration":"EVT_SYS_REBOOT", "description":"Device reboot request from application/web", "severity":"Info"},
        {"id":"505", "enumeration":"EVT_SYS_RESTART", "description":"GW/DC restarted with restart cause", "severity":"Info"},
        {"id":"506", "enumeration":"EVT_SYS_TIME_SET", "description":"Time set", "severity":"Info"},
        {"id":"507", "enumeration":"EVT_SYS_TIME_SYNCHRONISED", "description":"Time synchronized with NTP server", "severity":"Info"},
        {"id":"508", "enumeration":"EVT_SYS_NTP_ERROR", "description":"Error synchronizing time with NTP server", "severity":"Error"},
        {"id":"509", "enumeration":"EVT_SYS_MAIN_COVER_OPENED", "description":"GW/DC main cover opened", "severity":"Info"},
        {"id":"510", "enumeration":"EVT_SYS_MAIN_COVER_CLOSED", "description":"GW/DC main cover closed", "severity":"Info"},
        {"id":"511", "enumeration":"EVT_SYS_TERMINAL_COVER_OPENED", "description":"GW/DC device cover opened", "severity":"Info"},
        {"id":"512", "enumeration":"EVT_SYS_TERMINAL_COVER_CLOSED", "description":"GW/DC device cover closed", "severity":"Info"},
        {"id":"513", "enumeration":"EVT_SYS_FW_INTERNAL_ERROR", "description":"Firmware/application internal error", "severity":"Error"},
        {"id":"514", "enumeration":"EVT_SYS_CPU_OVERLOADED", "description":"CPU overloaded", "severity":"Warning"},
        {"id":"515", "enumeration":"EVT_SYS_VOL_MEM_LOW_LEVEL", "description":"Volatile memory (RAM) low level", "severity":"Warning"},
        {"id":"516", "enumeration":"EVT_SYS_NOVOL_MEM_LOW_LEVEL", "description":"Non-volatile memory (FLASH, root partition) low level", "severity":"Warning"},
        {"id":"517", "enumeration":"EVT_SYS_DATA_MEM_LOW_LEVEL", "description":"Non-volatile memory (FLASH, data partition) low level", "severity":"Warning"},
        {"id":"518", "enumeration":"EVT_SYS_RESET_KEY_PRESSED", "description":"Reset key pressed", "severity":"Info"},
        {"id":"519", "enumeration":"EVT_SYS_PHASE_L1_OUTAGE", "description":"Phase L1 outage", "severity":"Info"},
        {"id":"520", "enumeration":"EVT_SYS_PHASE_L2_OUTAGE", "description":"Phase L2 outage", "severity":"Info"},
        {"id":"521", "enumeration":"EVT_SYS_PHASE_L3_OUTAGE", "description":"Phase L3 outage", "severity":"Info"},
        {"id":"522", "enumeration":"EVT_SYS_PHASE_L1_RETURN", "description":"Phase L1 returned", "severity":"Info"},
        {"id":"523", "enumeration":"EVT_SYS_PHASE_L2_RETURN", "description":"Phase L2 returned", "severity":"Info"},
        {"id":"524", "enumeration":"EVT_SYS_PHASE_L3_RETURN", "description":"Phase L3 returned", "severity":"Info"},
        {"id":"525", "enumeration":"EVT_SYS_FULL_POWER_OUTAGE", "description":"Full power outage (all three phases outage)", "severity":"Warning"},
        {"id":"526", "enumeration":"EVT_SYS_BATTERY_DISCHARGED", "description":"Battery discharged", "severity":"Warning"},
        {"id":"527", "enumeration":"EVT_SYS_BATTERY_LOW_LEVEL", "description":"Battery low level", "severity":"Warning"},
        {"id":"528", "enumeration":"EVT_SYS_BOOT_PARTITION_SWITCH", "description":"Linux boot partition switched", "severity":"Warning"},
        {"id":"600", "enumeration":"EVT_WAN_WAN1_CONNECT", "description":"WAN1 connection established", "severity":"Info"},
        {"id":"601", "enumeration":"EVT_WAN_WAN1_DISCONNECT", "description":"WAN1 connection disconnected", "severity":"Info"},
        {"id":"602", "enumeration":"EVT_WAN_WAN1_CONNECT_FAIL", "description":"WAN1 connect fail", "severity":"Info"},
        {"id":"603", "enumeration":"EVT_WAN_WAN1_PING_FAIL", "description":"WAN1 heartbeat ping fail", "severity":"Info"},
        {"id":"604", "enumeration":"EVT_WAN_WAN2_CONNECT", "description":"WAN2 connection established", "severity":"Info"},
        {"id":"605", "enumeration":"EVT_WAN_WAN2_DISCONNECT", "description":"WAN2 connection disconnected", "severity":"Info"},
        {"id":"606", "enumeration":"EVT_WAN_WAN1_SIGNAL_LOW", "description":"WAN1 GSM signal level is low", "severity":"Warning"},
        {"id":"607", "enumeration":"EVT_WAN_WAN1_SIGNAL_RESTORED", "description":"WAN1 GSM signal level restored", "severity":"Info"},
        {"id":"608", "enumeration":"EVT_WAN_WAN2_CARRIER_UP", "description":"WAN2 carrier present, cable connect", "severity":"Info"},
        {"id":"609", "enumeration":"EVT_WAN_WAN2_CARRIER_DOWN", "description":"WAN2 carrier lost, cable disconnect", "severity":"Warning"},
        {"id":"610", "enumeration":"EVT_WAN_LAN_CARRIER_UP", "description":"LOC carrier present, cable connect", "severity":"Info"},
        {"id":"611", "enumeration":"EVT_WAN_LAN_CARRIER_DOWN", "description":"LOC carrier lost, cable disconnect", "severity":"Info"},
        {"id":"612", "enumeration":"EVT_WAN_WAN1_MODEM_NOT_DETECTED", "description":"WAN1 modem not detected", "severity":"Info"},
        {"id":"613", "enumeration":"EVT_WAN_WAN1_MODEM_SIM_ERROR", "description":"WAN1 modem SIM card error", "severity":"Error"},
        {"id":"614", "enumeration":"EVT_WAN_WAN1_MODEM_DETECTED", "description":"WAN1 modem detected", "severity":"Info"},
        {"id":"615", "enumeration":"EVT_WAN_WAN1_CMUX_ERROR", "description":"WAN1 modem CMUX error", "severity":"Error"},
        {"id":"616", "enumeration":"EVT_WAN_WAN1_MODEM_FW_UPGRADE_OK", "description":"WAN1 modem FW upgrade completed OK", "severity":"Info"},
        {"id":"617", "enumeration":"EVT_WAN_WAN1_MODEM_FW_UPGRADE_ERROR", "description":"WAN1 modem FW upgrade error", "severity":"Error"},
        {"id":"700", "enumeration":"EVT_CNTR_UPGRADE_STARTED", "description":"Upgrade started", "severity":"Info"},
        {"id":"701", "enumeration":"EVT_CNTR_UPGRADE_SUCCEEDED", "description":"Upgrade succeeded", "severity":"Info"},
        {"id":"702", "enumeration":"EVT_CNTR_UPGRADE_FAILED", "description":"Upgrade failed", "severity":"Error"},
        {"id":"703", "enumeration":"EVT_CNTR_PARAMETERS_SET", "description":"Parameters set", "severity":"Info"},
        {"id":"704", "enumeration":"EVT_CNTR_UPGRADE_STATUS", "description":"Upgrade progress status", "severity":"Info"},
        {"id":"705", "enumeration":"EVT_CNTR_UPGRADE_ROLLBACK", "description":"Upgrade rollback initiated", "severity":"Warning"},
        {"id":"706", "enumeration":"EVT_CNTR_UPGRADE_IMAGE_SIGNATURE", "description":"Invalid image signature", "severity":"Info"},
        {"id":"707", "enumeration":"EVT_CNTR_UPGRADE_CANCELLED", "description":"Upgrade cancelled", "severity":"Info"},
        {"id":"800", "enumeration":"EVT_MAC_METER_COMMISSIONED", "description":"Meter commissioned", "severity":"Info"},
        {"id":"801", "enumeration":"EVT_MAC_METER_NO_KEYS", "description":"Meter no keys", "severity":"Info"},
        {"id":"802", "enumeration":"EVT_MAC_METER_WRONG_KEYS", "description":"Meter wrong keys", "severity":"Info"},
        {"id":"803", "enumeration":"EVT_MAC_METER_LOST", "description":"Meter lost", "severity":"Info"},
        {"id":"804", "enumeration":"EVT_MAC_METER_REMOVED", "description":"Meter removed from list", "severity":"Info"},
        {"id":"805", "enumeration":"EVT_MAC_METER_UPGRADE_STARTED", "description":"Upgrade operation started", "severity":"Info"},
        {"id":"806", "enumeration":"EVT_MAC_METER_UPGRADE_COMPLETED", "description":"Upgrade operation completed", "severity":"Info"},
        {"id":"807", "enumeration":"EVT_MAC_METER_TIME_SYNC_FAILED", "description":"Meter time synchronization failed", "severity":"Info"},
        // {"id":"900", "enumeration":"EVT_METER_READY", "description":"Joined meter READY for use", "severity":"Info"},
        {"id":"901", "enumeration":"EVT_DATA_RESOURCE_CREATED", "description":"Data job created", "severity":"Info"},
        {"id":"902", "enumeration":"EVT_DATA_RESOURCE_CHANGED", "description":"Data job parameters changed", "severity":"Info"},
        {"id":"903", "enumeration":"EVT_DATA_RESOURCE_DELETED", "description":"Data job deleted", "severity":"Info"},
        {"id":"904", "enumeration":"EVT_DATA_RESOURCE_DELETION_FAILED", "description":"Data job deletion failed", "severity":"Info"},
        {"id":"905", "enumeration":"EVT_SCHEDULE_RESOURCE_STARTED", "description":"Scheduled job started", "severity":"Info"},
        {"id":"906", "enumeration":"EVT_ONDEMAND_RESOURCE_ACTIVATED", "description":"On demand job activated", "severity":"Info"},
        {"id":"907", "enumeration":"EVT_RESOURCE_ITERATION_OK", "description":"Data job data collection completed successful", "severity":"Info"},
        {"id":"908", "enumeration":"EVT_RESOURCE_ITERATION_NOT_COMPLETED", "description":"Data job data collection completed partly successful", "severity":"Info"},
        {"id":"909", "enumeration":"EVT_RESOURCE_ITERATION_FAILED", "description":"Job data collection completed not successful", "severity":"Info"},
        {"id":"910", "enumeration":"EVT_RESOURCE_ITERATION_EMPTY", "description":"Job data collection completed empty", "severity":"Info"},
        {"id":"911", "enumeration":"EVT_RESOURCE_ITERATION_STOPPED", "description":"Job data collection stopped", "severity":"Info"},
        {"id":"912", "enumeration":"EVT_SEND_DATA_RESOURCE", "description":"Job data request received", "severity":"Info"},
        {"id":"913", "enumeration":"EVT_CONFIG_RESOURCE_CHANGED", "description":"Config job parameters changed", "severity":"Info"},
        {"id":"914", "enumeration":"EVT_UPGRADE_FIRMWARE_FAILED", "description":"Upgrade firmware job finished not successful.", "severity":"Info"},
        {"id":"1000", "enumeration":"EVT_SEC_WEB_LOGIN_OK", "description":"User successfully logged into web portal", "severity":"Info"},
        // {"id":"1001", "enumeration":"EVT_SEC_WEB_LOGIN_CERT_MISMATCH", "description":"User web portal login failed, certificate mismatch", "severity":"Info"},
        {"id":"1002", "enumeration":"EVT_SEC_WEB_LOGIN_PASS_MISMATCH", "description":"User web portal login failed, password mismatch", "severity":"Info"},
        {"id":"1100", "enumeration":"EVT_SD_DATABASE_FULL", "description":"The database has reached the predefined size constraint", "severity":"Error"},
        {"id":"1101", "enumeration":"EVT_SD_DATABASE_ERROR", "description":"The database problem and it needs to be reinitialized", "severity":"Error"},
        {"id":"1102", "enumeration":"EVT_SD_DATABASE_REINIT", "description":"The database was reinitialized", "severity":"Info"},
        {"id":"1200", "enumeration":"EVT_SNMP_STARTED", "description":"SNMP daemon started", "severity":"Info"},
        {"id":"1201", "enumeration":"EVT_SNMP_STOPPED", "description":"SNMP daemon stopped", "severity":"Info"},
        {"id":"1202", "enumeration":"EVT_SNMP_PARAMS_CHANGED", "description":"SNMP parameters changed", "severity":"Info"},
        {"id":"1203", "enumeration":"EVT_SNMP_V3_CREDENTIAL_SET", "description":"SNMP v3 credential changed", "severity":"Info"},
        {"id":"1201", "enumeration":"EVT_SNMP_ENABLED", "description":"SNMP enabled", "severity":"Info"},
        {"id":"1201", "enumeration":"EVT_SNMP_DISABLED", "description":"SNMP disabled", "severity":"Info"}
    ]
};
module.exports = eventList;